name: "Bug Report"
description: "Encountered a bug? Report it here"
title: "Bug"
labels: [enhancement]
body:
  - type: markdown 
    attributes:
      value:
        ## Thanks for taking the time to fill out this bug report!
        
        "We're sorry that you've encountered an issue. If you need real-time help, join the [Discussions Forum](https://github.com/uni-notes/uni-notes/discussions)"
        
  - type: checkboxes 
    id: terms 
    attributes:
      label: Project Contribution
      description: This project has Contribution Guidelines that all participants are expected to understand and follow.
      options:
        - label: "I have read and agree to the project's [Contribution Guidelines](https://github.com/unnamed-project/.github/CODE_OF_CONDUCT.md)📜"
          required: true 
  - type: textarea 
    id: what-happened 
    attributes:
      label: "What happened?"
      description: |
        - Give a clear and concise description about the issue.
        - What is the expected outcome?
    validations: 
      required: true
  - type: textarea
    id: anything-else
    attributes:
      label: Anything Else🤔?
      description: Anything else that we should know about the issue?
    validations:
      required: false
